# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/
#      configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend dependency updates
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"

  # Backend dependency updates
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"

  # E2E dependency updates (assuming they're npm based in an e2e directory)
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "e2e"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
