# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend dependency updates
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*test*"
          - "vitest"
          - "vite"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "solid-js"
          - "axios"
          - "chart.js"
          - "@kobalte/core"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"

  # Backend dependency updates
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "black"
          - "flake8*"
          - "isort"
          - "pytest*"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "fastapi"
          - "uvicorn"
          - "pydantic*"
          - "sqlalchemy"
          - "alembic"
          - "jira"
          - "atlassian-python-api"
          - "pandas"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
