# YAML formatting configuration for yamlfmt
formatter:
  type: basic
  indent: 2
  line_ending: lf
  include_document_start: false
  retain_line_breaks: true
  disallow_anchors: false
  max_line_length: 0
