services:
  nginx:
    image: nginx:alpine
    container_name: jira-analyzer-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - jira-analyzer-network-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: jira-analyzer-backend-dev
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    volumes:
      - ./backend:/app
      - jira_analyzer_data:/app/instance
    expose:
      - "5000"
    ports:
      - "5678:5678"  # For debugpy
    networks:
      - jira-analyzer-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: jira-analyzer-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "3000"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - jira-analyzer-network-dev

networks:
  jira-analyzer-network-dev:
    driver: bridge

volumes:
  jira_analyzer_data:
    name: jira_analyzer_data_dev
