services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development-enhanced
    container_name: jira-analyzer-backend-dev
    # Only expose debug port, API access should be through Caddy
    ports:
      - "5678:5678"  # Python debugger port
    expose:
      - "8000"  # Expose to other containers, but not to host
    environment:
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=["http://localhost:${FRONTEND_PORT:-80}", "http://localhost:5173", "http://caddy:80"]
      # Development Configuration
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Testing Configuration
      - USE_MOCK_JIRA=${USE_MOCK_JIRA:-true}
      - USE_IN_MEMORY_DB=${USE_IN_MEMORY_DB:-false}
    volumes:
      - ./backend:/app
      - jira-analyzer-data:/app/data
    # Override the default command to remove --wait-for-client
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: jira-analyzer-frontend-dev
    # Only expose debug port, web access should be through Caddy
    ports:
      - "9229:9229"  # Node.js debugger port
    expose:
      - "5173"  # Expose to other containers, but not to host
    environment:
      - VITE_API_URL=/api
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  caddy:
    image: caddy:2-alpine
    container_name: jira-analyzer-caddy-dev
    ports:
      - "${FRONTEND_PORT:-80}:80"  # HTTP port
      - "443:443"  # HTTPS port
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  jira-analyzer-data:
  caddy_data:    # Persistent volume for Caddy SSL certificates
  caddy_config:  # Persistent volume for Caddy configuration

networks:
  default:
    name: jira-analyzer-network-dev
