services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jira-analyzer-backend
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - jira_analyzer_data:/app/instance
    networks:
      - jira-analyzer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jira-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - jira-analyzer-network

networks:
  jira-analyzer-network:
    driver: bridge

volumes:
  jira_analyzer_data:
    name: jira_analyzer_data
