name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests-checks:
    name: E2E Tests Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: "10"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"
          cache-dependency-path: "e2e-tests/pnpm-lock.yaml"

      - name: Install e2e-tests dependencies
        working-directory: ./e2e-tests
        run: pnpm install

      - name: Lint e2e-tests
        working-directory: ./e2e-tests
        run: |
          pnpm run lint:strict
          npx eslint --format stylish '*.{js,jsx,ts,tsx,json}'

      - name: Check e2e-tests formatting
        working-directory: ./e2e-tests
        run: pnpm run format:check

      - name: Type check e2e-tests
        working-directory: ./e2e-tests
        run: pnpm run type-check

  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: "10"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install system dependencies for canvas
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install pkg-config cairo pango libpng jpeg giflib librsvg
          fi
        shell: bash

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          pnpm install

          # Explicitly install the missing optional dependency for rollup
          if [ "$RUNNER_OS" == "Linux" ]; then
            # For Linux runners, ensure the correct platform-specific package is installed
            pnpm add -D @rollup/rollup-linux-x64-gnu
          fi

      - name: Lint frontend
        working-directory: ./frontend
        run: |
          pnpm run lint
          npx eslint --format stylish '*.{js,jsx,ts,tsx,json}'

      - name: Check frontend formatting
        working-directory: ./frontend
        run: pnpm run format:check

      - name: Type check frontend
        working-directory: ./frontend
        run: pnpm run type-check

      - name: Test frontend
        working-directory: ./frontend
        run: pnpm run test

  backend-checks:
    name: Backend Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Setup Python virtual environment
        working-directory: ./backend
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          pip install -r requirements.txt
          pip install ruff mypy bandit[toml]

      - name: Lint backend with Ruff
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          ruff check app tests

      - name: Format backend with Ruff
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          echo "Verifying formatting"
          ruff format --check app tests

      - name: Type check backend with MyPy
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          mypy app --exclude=app/migrations --ignore-missing-imports

      - name: Security check with Bandit
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          bandit -c pyproject.toml -r app

      - name: Run backend unit tests
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          pytest tests/unit -v

      - name: Run backend integration tests
        working-directory: ./backend
        run: |
          . .venv/bin/activate
          pytest tests/test_config.py tests/test_input_validation.py \
            tests/test_metric_calculations.py tests/test_api_metrics.py -v

  yaml-checks:
    name: YAML Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      - name: Check YAML formatting
        run: |
          yamlfmt -conf .yamlfmt.yml -lint .github/workflows/*.yml \
          .github/dependabot.yml docker-compose.yml docker-compose.dev.yml .yamllint.yml

  docker-build-test:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [e2e-tests-checks, frontend-checks, backend-checks, yaml-checks]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          load: true
          tags: jira-analyzer-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./frontend/Dockerfile.standalone
          build-args: |
            NODE_VERSION=23
            PNPM_VERSION=10.6.2

      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          load: true
          tags: jira-analyzer-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
