name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'e2e-tests/package-lock.json'

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "USE_MOCK_JIRA=true" >> .env
        echo "USE_IN_MEMORY_DB=true" >> .env

    - name: Check and stop any running services
      run: |
        if docker ps | grep -q "jira-analyzer"; then
          echo "Services are already running. Shutting them down..."
          docker-compose -f docker-compose.dev.yml down
        fi

    - name: Start backend with Docker Compose
      run: |
        docker-compose -f docker-compose.dev.yml up -d

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install -g pnpm
        pnpm install

    - name: Install e2e-tests dependencies
      run: |
        cd e2e-tests
        npm install

    - name: Install Playwright browsers
      run: |
        cd e2e-tests
        npx playwright install --with-deps

    - name: Lint and format e2e-tests
      run: |
        cd e2e-tests
        npm run lint
        npm run format:check

    - name: Run end-to-end tests
      run: |
        cd e2e-tests
        chmod +x run-tests.sh
        CI=true npm run run-tests

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: e2e-tests/playwright-report/
        retention-days: 30

    - name: Stop Docker Compose
      if: always()
      run: |
        docker-compose -f docker-compose.dev.yml down
